### ISSUE TITLE
Fix setup

### ISSUE THREAD

**Issue by Super-T02** [DHBW-Smart-Rollerz/smarty_workspace#4]
It seems that our configurations are converging:
![image](https://github.com/user-attachments/assets/206a8194-9e5c-41ac-ba83-ed2b0af0f358)

DoD: Setup works for pipeline and local installation

**Comment by jonasweihing** [comment]
This is due to rosdep being already initialized in the container of the build test and not on the system.

**Comment by Super-T02** [comment]
Resolved
